### ISSUE TITLE
Generating tests infinite load

### ISSUE THREAD

**Issue by Portur** [Codium-ai/codiumai-jetbrains-release#104]
Hi,

Highlighting code and clicking on context menu item "generate tests" brings up the window to provide tests and other code suggestions. However the window is loading infinitely.

![image](https://github.com/Codium-ai/codiumai-jetbrains-release/assets/24350810/dece2a2f-d040-40ed-b803-74f84f1c0562)

---
Build info

IntelliJ IDEA 2023.2.1 (Ultimate Edition)
Build #IU-232.9559.62, built on August 23, 2023
Runtime version: 17.0.8+7-b1000.8 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4048M
Cores: 10
Metal Rendering is ON
Registry:
    ide.experimental.ui=true

Kotlin: 232-1.9.0-IJ9559.62

┆Issue is synchronized with this [Trello card](https://trello.com/c/MhhqtsfO) by [Unito](https://www.unito.io)

**Comment by Portur** [comment]
Closing the IDE and retying the process worked.

It asked me to log in again first, and worked after.

**Comment by aldanchenko** [comment]
Hi @Portur 

Thanks for reporting. Were there any errors (notifications with errors)?

Best regards,
Alex

**Comment by ArtsiomCh** [comment]
Probably our backend been overload in first attempt...
Please let us know if it happened again!
