### ISSUE TITLE
[IntelliJ IDEA 2022.3.3] login timeout

### ISSUE THREAD

**Issue by neilwyh** [Codium-ai/codiumai-jetbrains-release#109]
Codeium plugin version: 1.2.87

login request url: http://127.0.0.1:62292/auth?state=...&access_token=...
output: **Timed out after 1s**

After restarting IDEA, you can log in, but autocomplete is almost unusable, it keeps spinning round and waiting, at which point logging out of the account again reveals that you can't log in again.

┆Issue is synchronized with this [Trello card](https://trello.com/c/iIDTkr1W) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Hi, this repository is about CodiumAI plugin. Codeium plugin is developed by another company. Please report the issue in their bug tracker.

**Comment by neilwyh** [comment]
> Hi, this repository is about CodiumAI plugin. Codeium plugin is developed by another company. Please report the issue in their bug tracker.

The spelling of the two names is too close together. Sorry.
