### ISSUE TITLE
use actions and/or intentions instead of inline "CodiumAI: Test this" text

### ISSUE THREAD

**Issue by keturn** [Codium-ai/codiumai-jetbrains-release#120]
I appreciate the IDE integration, but can we remove the "CodiumAI: Test this" text that's inserted inline before every class and method definition? That text adds noise to the code view without providing any new information, and isn't (or shouldn't) be necessary to calling "test this" when I need to. Thanks!

┆Issue is synchronized with this [Trello card](https://trello.com/c/4Qtqiay7) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Thanks for suggestion!
cc @GadiZimerman

**Comment by DedyKredo** [comment]
@keturn, thanks for the feedback. We will add the option to disable the links and trigger using a keyboard shortcut. We'll update here once done; it would take a few weeks as we're currently working to add some very exciting new capabilities to our Jetbrains plugin.

**Comment by ArtsiomCh** [comment]
Ability to disable inlay added in 0.6.12
