### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by RaederDev** [Codium-ai/codiumai-jetbrains-release#13]
I get an "Invalid syntax" error when trying to generate a test for a TS generator function that yields a tuple:
```ts
function* nextActiveDay(
  config: AlarmConfiguration,
  filteredLessons: Array<Lesson>,
  course: Course,
  courseConfig: CourseConfiguration,
): Generator<[date: Date, lesson: Lesson], null> {
  yield [new Date(), filteredLessons[0]];
  return null;
}
```
  
(I removed the real code for brevity sake, but this also triggers the same error).

**Comment by ArtsiomCh** [comment]
Hi @RaederDev 
Explored your code and apparently we don't support _generator functions_ at the moment... :( 
But that's in our plans. :)
So, stay tuned and in the meantime try latest 0.4.9 with numerous improvements.
