### ISSUE TITLE
Manual authorization code option

### ISSUE THREAD

**Issue by meza** [Codium-ai/codiumai-jetbrains-release#14]
When signing in, the only way to do it right now is through this window.

![image](https://user-images.githubusercontent.com/211977/228851277-b7d6174d-4085-42d3-ae49-23994883367d.png)

However, when there is no browser present (say in a WSL environment), there is no alternative and the login spinner will just stay there indefinitely.

Github has a way to authorize by copying codes and it's how copilot works for example. After a while, it'll detect that the auth hasn't happened yet and offer a manual way of completing the process.

┆Issue is synchronized with this [Trello card](https://trello.com/c/9CVHAGf3) by [Unito](https://www.unito.io)

**Comment by almog-lv** [comment]
Thank you @meza we added a task to optimize the login process, thanks for raising this issue with us!

**Comment by GadiZimerman** [comment]
@meza Hello, we've changed our login to be based on browser, can you please check if your problem is solved?

**Comment by meza** [comment]
Will do shortly, thanks!
