### ISSUE TITLE
login failure

### ISSUE THREAD

**Issue by Cheng455153666** [Codium-ai/codiumai-jetbrains-release#140]
1. First, i try to click sign in with github and google, but it does't work.
2. So, i sign in with email, click sign in with github and google on website. told me like this image.

<img width="461" alt="image" src="https://github.com/Codium-ai/codiumai-jetbrains-release/assets/11585827/55d7a614-6540-495d-bf3a-275c9fda0f8e">

**Comment by ArtsiomCh** [comment]
Just checked, **github** and **google** sign in from plugin works. 
And from web-site (Signing using email) is broken. We'll investigate, Thank you got reporting!
Please, try to Signing using email directly. i.e. input your email into the filed and you'll receive sign in link (sent to provided email).

PS But if you behind any proxy/firewall that blocks connections to such recourses then it will not work. It most likely will not work from the web-site (Signing using email) either (as it redirect to github or google accordingly).

**Comment by ArtsiomCh** [comment]
Fixed
Thanks for reporting!
