### ISSUE TITLE
Can't login using google or email as the url is bad

### ISSUE THREAD

**Issue by AmrAli25** [Codium-ai/codiumai-jetbrains-release#197]
when trying to log in using any option on the page provided it gives an error 404 page not found 
<img width="460" alt="image" src="https://github.com/Codium-ai/codiumai-jetbrains-release/assets/32249479/90b187f5-bd07-4002-9e4d-3ffc4808db03">

and the URL provided is like this (http://localhost:63342/codium.codium/)
<img width="1964" alt="image" src="https://github.com/Codium-ai/codiumai-jetbrains-release/assets/32249479/d7f8c011-7081-4f97-830b-a4fe34b3bf3f">
so what is the problem and how to fix this

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Does it happened for you all the time or it gone already?
Do you have any firewall/proxy on your side?
Do you have any restriction set for inbound connection from Internet to your IDE?

**Comment by AmrAli25** [comment]
Thanks for the reply 

It has already been fixed after two days of not trying to sign in
