### ISSUE TITLE
UI: Icon is just a itsy bitsy tiny dot

### ISSUE THREAD

**Issue by mjsilva** [Codium-ai/codiumai-jetbrains-release#20]
![web-demo – CtbViewer tsx 2023-04-13 at 10 12 14 am](https://user-images.githubusercontent.com/158554/231613115-794a8ced-4ce2-48fb-ad29-a3e82a3d94a6.jpg)

very hard to find :)

┆Issue is synchronized with this [Trello card](https://trello.com/c/GdBLV0tw) by [Unito](https://www.unito.io)

**Comment by GadiZimerman** [comment]
Thanks for the feedback, can you please help us locate the issue by providing your OS, JetBrains product and version and selected theme?

**Comment by almog-lv** [comment]
Hey, @mjsilva can you please help us by providing your OS and which IDE are you using? (a version will be also very helpful). Thanks!
