### ISSUE TITLE
Troubles with brackets in PyCharm Community

### ISSUE THREAD

**Issue by Ar-Yakimov** [Codium-ai/codiumai-jetbrains-release#203]
For some reason, AI uses brackets ` instead of ', " or ''' in its Python code listings.

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Are see it in generated tests or in chat messages?

**Comment by ArtsiomCh** [comment]
Can't reproduce the issue. Presume it was some random AI glitch. 
@Ar-Yakimov Are you still see it? If so, what's the way to reproduce?

**Comment by ArtsiomCh** [comment]
Reproduced, will fix
Thanks again for reporting!

**Comment by ArtsiomCh** [comment]
fixed in 0.7.24
