### ISSUE TITLE
chat screen becomes white

### ISSUE THREAD

**Issue by Shivamj4112** [Codium-ai/codiumai-jetbrains-release#215]
![Screenshot 2024-03-29 103204](https://github.com/Codium-ai/codiumai-jetbrains-release/assets/101393149/323f5f9e-3a2a-441a-9bb2-3ec338685daf)

**Comment by almog-lv** [comment]
@Shivamj4112 for some reason I can't load your image, can you please tell me which IDE are you using? thanks

**Comment by Shivamj4112** [comment]
Android Studio

**Comment by Shivamj4112** [comment]
![Screenshot 2024-03-29 113727](https://github.com/Codium-ai/codiumai-jetbrains-release/assets/101393149/5c3d9905-bf56-47a9-8a7e-8206ac18e4e0)


I have changed the boot runtime as you or your team mentioned in the reviews.

**Comment by almog-lv** [comment]
@almog-lv this issue is an issue with Android Studio, managed by Google. If you search in Google you will find many other plugins suffer from the same issue. It happens to all webview-based plugin. I suggest you downgrade the version to 0.7.24, it will work for you until Google solves this issue. Thanks

**Comment by Shivamj4112** [comment]
> @almog-lv this issue is an issue with Android Studio, managed by Google. If you search in Google you will find many other plugins suffer from the same issue. It happens to all webview-based plugin. I suggest you downgrade the version to 0.7.24, it will work for you until Google solves this issue. Thanks

Hello, this solution works, so if anyone else encounters the same issue, you can use this solution. I also want the Codium-ai to be improved, which is why I have deleted my previous reviews and added a new one for this.

**Comment by almog-lv** [comment]
Thank you @Shivamj4112 !
