### ISSUE TITLE
Codiumate ask throws an error when trying to correct your question.

### ISSUE THREAD

**Issue by cmrgKoradir** [Codium-ai/codiumai-jetbrains-release#223]
So I don't know how to add multiple files to Codiumate Chat's context. To get around that, I thought I'd try the only other available mode, `Workspace - Committed Changes`.

First, Codiumate complained that none of the changes on the current branch, compared to `master` have anything to do with what I'm asking about. (which is correct), and asked me to provide context.

So I continued the chat
and told it to use a certain class and its dependencies as a context.

And then noticed that I accidentally gave it an interface rather than an implementation.

So after Codium described to me what a generic general solution could potentially do to address the issue,
I pressed the `x` on my previous question.
This deleted the question but not the answer to it (weird, imho),

and I told it again that the context was the implementation class and its dependencies.

This, however, Codiumate wasn't able to process:
![image](https://github.com/Codium-ai/codiumai-jetbrains-release/assets/64977051/4c8ec9ee-d238-4881-ae92-5001239f9450)

This is
- Codiumate `0.7.33` for
- Intellij Ultimate `2024.1`, on
- Ubuntu `22.04.4 LTS` using the KDE desktop

**Comment by cmrgKoradir** [comment]
> For now you can use that trick with Committed Changes.

@ArtsiomCh actually, I can't. Codiumate will still insist that it would need to see the code for the class I named and just gives me "ah, you would probably find the solution in either that class or its dependencies" and that I would provide more context, which is not very useful :sweat_smile: 

I would expect it to know to look at the files containing the class mentioned

**Comment by ArtsiomCh** [comment]
Files you want be seen as context need be in Committed Changes diff.
Unfortunately for now there's no other way to explicitly point Codiumate to the source 😞

**Comment by ArtsiomCh** [comment]
Option to add Manual context (for Code Block mode) is added in 0.7.34
Hope that will help!
