### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by Vampire-DIO** [Codium-ai/codiumai-jetbrains-release#24]
![image](https://user-images.githubusercontent.com/48446966/235047510-c4728a22-4376-4fd7-9dcc-a08f5d96e6d6.png)

I can't login to the plugin when I use it in idea, and I've tried both Google login and GitHub login.

┆Issue is synchronized with this [Trello card](https://trello.com/c/58PpxtUC) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Hi! Thanks for reporting
Are you behind any firewall/proxy that could block connection to Google websites?

**Comment by Vampire-DIO** [comment]
Thank you for your reply. Maybe that's the problem. I can't locate it either.
Is codeium plug-in also maintained by you? This plugin works fine on vscode, but has problems with idea.
![image](https://user-images.githubusercontent.com/48446966/236418440-f2e67608-cdb0-4bbc-b28e-376ea7e3fa4b.png)

**Comment by Vampire-DIO** [comment]
> Hi! Thanks for reporting Are you behind any firewall/proxy that could block connection to Google websites?

Thank you for your reply. Maybe that's the problem. I can't locate it either.
Is codeium plug-in also maintained by you? This plugin works fine on vscode, but has problems with idea.
![image](https://user-images.githubusercontent.com/48446966/236418722-4d8aeb6c-c583-4306-9e66-218db0b0ae16.png)

![image](https://user-images.githubusercontent.com/48446966/236418843-61f251f4-9ae1-4074-84d4-227ccee893aa.png)

**Comment by ArtsiomCh** [comment]
We use Google services under the hood of the plugin. So access to Google is essential for plugin to work. Please make sure it's not blocked on your side (or by government in your location)

Codeium plugin is not maintained by us, so please contact is t developers for any related issues.

**Comment by Vampire-DIO** [comment]
> We use Google services under the hood of the plugin. So access to Google is essential for plugin to work. Please make sure it's not blocked on your side (or by government in your location)
> 
> Codeium plugin is not maintained by us, so please contact is t developers for any related issues.

ok, thanks

**Comment by qiannianlei** [comment]
![image](https://github.com/Codium-ai/codiumai-jetbrains-release/assets/8662890/07e36b49-b780-4a53-b695-782980e7a535)

登录完成之后，在phpstorm编辑器里面提示：认证失败

![image](https://github.com/Codium-ai/codiumai-jetbrains-release/assets/8662890/160567ae-63a2-4e42-a5e7-2d29f1c11677)

**Comment by ArtsiomCh** [comment]
@Vampire-DIO this repository is about **CodiumAI** plugin (Codiumate). Codeium is not our product.
Please report the problem in **Codeium** issue tracker.
