### ISSUE TITLE
[1.8.42] Codium stopped working in RustRover 2024.1

### ISSUE THREAD

**Issue by marvin-hansen** [Codium-ai/codiumai-jetbrains-release#243]
This issue is fairly consistent since the  2024.1 update came out.

1) Codium assistant pane turns gray; for real. See picture below.
2) Codium looses connection to the server.  

I did a re-install, which fixed the issue for maybe ten minutes, but then I was back to square one.

Would be great if someone would take a look and see if this can be fixed. 

Thank you.

## Details
MacOS Sonoma 14.5
Apple M3 Max

RustRover 2024.1
Build #RR-241.15989.199, built on May 18, 2024
Runtime version: 17.0.10+1-b1207.14 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Metal Rendering is ON
Non-Bundled Plugins:
  idea.plugin.protoeditor (241.15989.49)
  Statistic (4.2.14)
  **com.codeium.intellij (1.8.42)**
  String Manipulation (9.14.1)
  mobi.hsz.idea.gitignore (4.5.3)
  izhangzhihao.rainbow.brackets (2024.2.4-241)
  com.github.dinbtechit.vscodetheme (1.10.10)

## Image 

<img width="602" alt="Screenshot 2024-06-07 at 10 23 10 AM" src="https://github.com/Codium-ai/codiumai-jetbrains-release/assets/24190940/29f4248f-4460-41a9-bae5-ececd5304b1e">

**Comment by marvin-hansen** [comment]
Fixed with last updated to 1.8.58

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Also this repository is for CodiumAI plugin Codiumate, while issue was with Codeium plugin.
