### ISSUE TITLE
installed on intellj free version, get message "Codiumate Plugin uses JCEF (Java Chromium Embedded Framework) ..." Does this mean it worked or I need to fix it?

### ISSUE THREAD

**Issue by nutmix** [Codium-ai/codiumai-jetbrains-release#244]
After installing codium on intellj free version, and logging in, I get this message appear on top left of UI:

Codiumate Plugin uses JCEF (Java Chromium Embedded Framework) to create a webview component in the plugin's tool window.
By default, most IntelliJ-based IDEs come with a boot runtime that includes JCEF.
However, Android Studio (and some other versions of IntelliJ-based IDEs) utilize a boot runtime lacking JCEF, which prevents the plugin from loading in these environments.
Also in some cases JCEF could persist but not been initialised.

Does this mean everyting is ok, or something failed?  

Does it mean I need to fix it, is it just a message everyone gets?

If I fix it, how do I know if the fix worked?

Also, there is a codium button on right hand side of IDE, but when I click this, it opens a message with "how to generate test with codiummate"... This message is fixed, there is no way to acknowledge or remove it, so it appears that the codiumn button has no purpose (other than to show a single message).

Also, unlike copilot, I cant see any evidence of codium working. If I type, there are no suggestions.

I notice the weird message in the top left is in a window called "codiumate chat". Why would I want chat?  I just want AI code assist like copilot.

Intellij 2024.1.1 community edition
Windows 10

**Comment by nutmix** [comment]
Ok, I could not find any documentation on how to actually use codium in intellij, but I did find that the free version doesnt support code completion, so, arguably, is completely useless.   This is a same, as copilot is excellent but its intellij plugin is unstable and unusable.   Back to copilot.

**Comment by almog-lv** [comment]
Hey @nutmix 
Codiumate plugin for JetBrains is a code assistant tool that helps developers to code and test with ease and confidence. The main focus of Codiumate is writing tests and improving your code quality. Code Completion is a new capability we added to Codiumate (currently available only in VSCode and for paying users, soon in JetBrains), and the main difference between Codiumate's code completion and the competitors is that Codiumate can focus on a task plan, using the Task Agent tool in the chat. I recommend you read more about the capabilities of Codiumate in our website - [www.codium.ai](www.codium.ai), which is NOT an ordinary code completion plugin. 
The issue you described with JCEF is solvable mostly, if you follow the instructions in our docs (after you fix it, you will see the Codiumate Chat panel).
