### ISSUE TITLE
Not able to login to Codium in PyCharm

### ISSUE THREAD

**Issue by owaisjilani** [Codium-ai/codiumai-jetbrains-release#245]

**Comment by ArtsiomCh** [comment]
Any details?
Are you on Linux with KDE?
Any errors shown by IDE?

**Comment by Temyxxa** [comment]
> _No description provided._

Same problem. No errors shown, appears on Ubuntu 22.04 and Windows 11, if you login using a token, the plugin shows endless loading. Treatment:
1. Navigate to the "Help" -> "Find Action..." and find(type) "Registry". Here disable ide.browser.jcef.sandbox.enable option.
2. Close IDE and delete .codeium directory in your home directory
3. Profit!

**Comment by hhstore** [comment]
- +1 
- No errors shown.

## env:

- macOS: `12.7.5`
- m1 Mac
- `PyCharm 2024.1.4 `

**Comment by hhstore** [comment]
> > _No description provided._
> 
> Same problem. No errors shown, appears on Ubuntu 22.04 and Windows 11, if you login using a token, the plugin shows endless loading. Treatment:
> 
> 1. Navigate to the "Help" -> "Find Action..." and find(type) "Registry". Here disable ide.browser.jcef.sandbox.enable option.
> 2. Close IDE and delete .codeium directory in your home directory
> 3. Profit!


- not works for me.
- +1 
- No errors shown.

## env:

- macOS: `12.7.5`
- m1 Mac
- `PyCharm 2024.1.4 `

**Comment by hhstore** [comment]
When clicking on the login button, there is no `pop-up login page`, no response, and no obvious error.

**Comment by hhstore** [comment]
## Solution:

- It conflicts with the IDE's `proxy settings`, you need to check `no proxy`, you can't set `proxy`. 
- Select `no proxy`, and you can `log in` normally.  
- This should be a bug, setting `proxy` to some users, is required.


<img width="700" alt="image" src="https://github.com/user-attachments/assets/15791e7d-73ca-46b8-8f60-ed5eff25e96b">

**Comment by ArtsiomCh** [comment]
This issue tracker is about **Codiumate - Code, test and review with confidence - by CodiumAI**
Please report the issue to **Codeium** authors/maintainers.

**Comment by Irratzo** [comment]
I also could not log in to Codeium anymore in PyCharm 2024.1.6, Codeium 1.14.11. @Temyxxa's solution [above](https://github.com/Codium-ai/codiumai-jetbrains-release/issues/245#issuecomment-2205467438) resolved the issue for me. Thank you.

**Comment by Temyxxa** [comment]
> I also could not log in to Codeium anymore in PyCharm 2024.1.6, Codeium 1.14.11. @Temyxxa's solution [above](https://github.com/Codium-ai/codiumai-jetbrains-release/issues/245#issuecomment-2205467438) resolved the issue for me. I only needed to do step 1., not step 2., to resolve the issue, though. Thank you.
> 
> However, after update to Codeium 1.14.14, I reverted step 1. (re-enabled Registry entry ide.browser.jcef.sandbox.enable). Logged out of Codeium. Logged in again. It worked. So maybe, just the update was needed.

I thought step 2 was more important. I did the first step already turning it on and off, and without deleting the folder it didn't work for me.
But starting with about version pyharm 2024.2 I haven't seen this problem at all.
In any case, I'm glad I helped you!

**Comment by almog-lv** [comment]
@Irratzo @Temyxxa This is a different tool, by a different company. We are CodiumAI and our tool is called **Codiumate**
https://plugins.jetbrains.com/plugin/21206-codiumate--code-test-and-review-with-confidence--by-codiumai

**Comment by Irratzo** [comment]
@almog-lv Thank you for pointing this out. My apologies for the confusion. Googling the error brought this thread as one of the first result ...

**Comment by brunoschmidt** [comment]
> > _No description provided._
> 
> Same problem. No errors shown, appears on Ubuntu 22.04 and Windows 11, if you login using a token, the plugin shows endless loading. Treatment:
> 
> 1. Navigate to the "Help" -> "Find Action..." and find(type) "Registry". Here disable ide.browser.jcef.sandbox.enable option.
> 2. Close IDE and delete .codeium directory in your home directory
> 3. Profit!

This was exactly right.
Before right after the login on the browser, the redirect to 127.0.0.1 would give an error because Codeium could not listen to the connection.
Without the sandbox it just works.

**Comment by dinukaly** [comment]
> ## Solution:
> * ✅ @ArtsiomCh @Temyxxa @owaisjilani @tombrewsviews
> * ✅ It conflicts with the IDE's `proxy settings`, you need to check `no proxy`, you can't set `proxy`.
> * ✅ Select `no proxy`, and you can `log in` normally.
> * ✅ This should be a `bug`, setting `proxy` to some users, is required.
> 
> <img alt="image" width="700" src="https://private-user-images.githubusercontent.com/3252130/348786716-15791e7d-73ca-46b8-8f60-ed5eff25e96b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMTA2NzQsIm5iZiI6MTcyODExMDM3NCwicGF0aCI6Ii8zMjUyMTMwLzM0ODc4NjcxNi0xNTc5MWU3ZC03M2NhLTQ2YjgtOGY2MC1lZDVlZmYyNWU5NmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDVUMDYzOTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDIxYThlOTUyOTJiMDVlMDk3N2FkZDY0ZDhkZGZiMjYzOTZjZDQyZTM3ZDEzZDdhODk4ZGYzODRjZTRjZGNhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.V8O0cqyNXpnT9zZqQ7TjnNB-VBtzN_vyPFpM65Fdx-c">

this is the exact solution ✅

**Comment by ArtsiomCh** [comment]
@dinukaly are you talking about **Codium** plugin or about **Qodo Gen** (formerly Codiumate) plugin?
Cause our plugin (Qodo Gen) is able to work with IDE proxy settings.
