### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by YJonmo** [Codium-ai/codiumai-jetbrains-release#246]
Hi there,

Thanks for this work.

I just installed it on VsCode (V 0.9.3). 
I am trying to follow the YouTube tutorial but Codium does not give me the options that I can see in the videos. 
the options are inactive. Here is an example:

<img width="582" alt="image" src="https://github.com/Codium-ai/codiumai-jetbrains-release/assets/12040950/3138a417-a14c-4e7a-b1ac-e4dc418b627c">

**Comment by ArtsiomCh** [comment]
Please move to correspondent VSC extension issue tracker:
https://github.com/Codium-ai/codiumai-vscode-release/issues
