### ISSUE TITLE
Unable to opt out of sharing data with Codium AI from settings

### ISSUE THREAD

**Issue by nonoash** [Codium-ai/codiumai-jetbrains-release#248]
I wanted to try the new opt out setting from the plugin instead of sending a mail, unfortunately upon ticking the option, the process hangs, retries 10 times and gives an error.

I get a notification
> It seems we were unable to update your data collection setting, please try again later.

and logs:
``WARN - #ai.codium.net.CodiumNetworkClient - Failed to execute `/v2/users` call (attempt 10/10): {"detail":"You can only optout for yourself"}``

Not sure what "You can only optout for yourself" means in this case, i'm sole admin of my setup.
Win10 
Pycharm 2024.1.3
Codiumate 0.8.2

It does say retry later and it's the first few time i tried today but i wanted to know if its indeed temporary on your side or if i have a problem.

**2nd question** The opt out is account based am i correct? So if i use vscode i won't need to re-opt out (once the setting is available on vscode)

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Reproduced, we'll investigate.
PS and yes, opt-out is account based, so it should work for the whole account (i.e. in VSCode as well)

**Comment by ArtsiomCh** [comment]
Fixed in 0.8.3
