### ISSUE TITLE
Failed to execute 'completions' network request: stream was reset: INTERNAL_ERROR

### ISSUE THREAD

**Issue by yoh-m** [Codium-ai/codiumai-jetbrains-release#25]
Hi,

Just discovered Codium and wanted to give it a try!

I installed the JetBrains plugin on PHPStorm, logged in, and opened a typescript project, then generated tests for a class; the test cases are properly listed, but in the Test code part I have a small readonly input saying "Failed to execute 'completions' network request: stream was reset: INTERNAL_ERROR".

Tried to restart PHPStorm a few times, re-generating tests, I always get the same error

┆Issue is synchronized with this [Trello card](https://trello.com/c/qiNzPXuE) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Fixed at 0.5.0 version.
