### ISSUE TITLE
How to handle the login issue when Codium cannot be used in Idea and PyCharm

### ISSUE THREAD

**Issue by lyx3314844** [Codium-ai/codiumai-jetbrains-release#254]
![Uploading 微信图片_20240729115259.png…]()

**Comment by lyx3314844** [comment]
WebStorm 2024.1.5
Build #WS-241.18034.50, built on June 19, 2024
Licensed to Deirdre Boyle
Subscription is active until July 24, 2025.
For educational use only.
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  aws.toolkit.core (3.20-241)
  amazon.q (3.20-241)
  com.codeium.intellij (1.10.6)
  com.service.char.format (1.0.0)
  jones.restarteslintaction.restart-eslint-action (0.0.1)
  codiumai.codiumai (0.9.1)
  com.sourcegraph.jetbrains (6.0.16)
  co.bito.bito-intellij (1.3.7)
  aws.toolkit (3.20-241)

**Comment by lyx3314844** [comment]
omething went wrong and we can't determine the exact error. Please, try again. Submit a ticket if the issue persists to support@codium.ai with requestId=284bcfb1-fde0-4b54-82a6-073d38b467ca

**Comment by lyx3314844** [comment]
部分使用我们 JetBrains 插件的中国大陆用户报告了此行为，这与 Firebase 登录被阻止有关。使用 VS Code IDE 可解决此问题。什么时候可以解决这个问题？

**Comment by ArtsiomCh** [comment]
@lyx3314844 from what I see in our logs from your latest login attempts: the callback from us (codium.ai) to your IDE is not passed thought your firewall/proxy. Ca you please check it settings and let callbacks from codium.ai passing to your `/localhost` ?

**Comment by ArtsiomCh** [comment]
@lyx3314844 lets move here with your issue

**Comment by lyx3314844** [comment]
![QQ_1722349327589](https://github.com/user-attachments/assets/765926f3-95bd-48c1-824d-5ebe7439a302)

**Comment by lyx3314844** [comment]
I have turned off both the firewall and proxy, but I still cannot use Codeium. But I can log in to your Codium AI official website normally through Google Chrome, there is no problem. If Codeium logs in to Idea, it will fail, unable to load the browser, and may even result in errors 401 or 404

**Comment by lyx3314844** [comment]
![QQ_1722353194147](https://github.com/user-attachments/assets/f965d577-8421-4ce8-a134-cd4f2b6cfb17)

**Comment by lyx3314844** [comment]
![Uploading QQ_1722357790104.png…]()

**Comment by lyx3314844** [comment]
![Uploading QQ_1722357790104.png…]()

**Comment by lyx3314844** [comment]
![Uploading   ##QQ_1722358140666.png…]

**Comment by lyx3314844** [comment]
![Uploading a8a92ec082523361e1d3c673de7d0c06.png…]()

**Comment by lyx3314844** [comment]
![Uploading 71ce0877267811e45c231cb720ecaf55.png…]()

**Comment by lyx3314844** [comment]
![71ce0877267811e45c231cb720ecaf55](https://github.com/user-attachments/assets/c63a8d1e-42be-4b89-939b-d04bb2604cb3)

**Comment by lyx3314844** [comment]
After logging in to IDEA and redirecting to Google browser, Codium will encounter the 404 error shown in the image above.

**Comment by lyx3314844** [comment]
![QQ_1722392454665](https://github.com/user-attachments/assets/4edbeb5b-91a1-4418-a889-fb4bdc0f46e1)

**Comment by lyx3314844** [comment]
I can use VSCode normally, but after a long time, I still can't open it in IDEA. Could you please continue to investigate

**Comment by lyx3314844** [comment]
@ArtsiomCh   I still can't use codium on Idea. Could you please help me check it

**Comment by lyx3314844** [comment]
@ArtsiomCh

**Comment by lyx3314844** [comment]
Please note that the proxy below has been completely banned by me through the local policy group. But I still couldn't access Codium AI, and in the end, I found out that only by manually using this VPN proxy could I open and block this website

**Comment by lyx3314844** [comment]
![Uploading QQ_1722500657335.png…]()

**Comment by lyx3314844** [comment]
![QQ_1722500657335](https://github.com/user-attachments/assets/104fe36f-963b-4afd-ae61-5a77c0324389)

**Comment by lyx3314844** [comment]
![QQ_1722500749747](https://github.com/user-attachments/assets/cb6ef11d-c168-402a-b6ac-8b18b1bc9d4b)

**Comment by lyx3314844** [comment]
The above agents, including the protective wall, have been completely shut down, and I have refreshed the Dns cache. Mr. ArtsiomCh, please don't mind my trouble. I am also helping our Chinese users deal with this issue. Looking forward to your reply. Thank you. The image above is in Chinese. If you don't understand it, you can use translation software to view it

**Comment by ArtsiomCh** [comment]
@lyx3314844 Can you provide step by step flow what you do and what you see when try to login in our plugin?

**Comment by lyx3314844** [comment]
I saw it. After logging in to Idea and then logging in to Codeium AI, it will redirect to Google Chrome to load. My firewall and proxy have been turned off for a long time. But the page keeps loading. I have tried many ways but couldn't find the reason

**Comment by lyx3314844** [comment]
@ArtsiomCh 
Firstly, if you want to use VPN, you need to disable the use of Windows Firewall, log in to VPN, and turn off the proxy. Check the version of your computer, and if it is the Home Student version, establish a local strategy. To prevent the agent from automatically opening. Upon entering Idea and logging in to Codegate, you will see three login methods. Choosing one will redirect you to Google for loading, which keeps loading. However, there is still no response, but the host is no longer rejecting the connection. I am still investigating,

**Comment by lyx3314844** [comment]
@ArtsiomCh  Firstly, when I use VPN to log in to the external network, I must disable the firewall and proxy. The firewall is simple, but the proxy is a troublesome task as it automatically opens and blocks the external network. You need to check if your computer is the Home Student version and if there is a local policy. If not, you need to create one yourself and use the cmd command. Then log in to Codium AI by entering Idea. Haha, I can successfully enter now. thank you. Thank you very much for your help. I also recommend codium ai to enter China's big market for our Chinese people

**Comment by ArtsiomCh** [comment]
Glad to hear you finally ma it!
And yeah, connecting from China is really tricky due to it firewall...

**Comment by lyx3314844** [comment]
![Uploading edb0a0281a258568bea87c37b70935ec_720.jpg…]()

**Comment by lyx3314844** [comment]
![Uploading edb0a0281a258568bea87c37b70935ec_720.jpg…]()

**Comment by lyx3314844** [comment]
@ArtsiomCh  I can't do it again. I successfully logged in to Idea once yesterday, but it failed. The local policy group I set up to block proxies has also failed, so I came up with another solution. I upgraded my computer to Windows 10 Professional version, and now I can use the local policy group to block proxies with confidence. But once again using Idea to log in to Codeium, it failed. It's really unlucky. I have sent you the successful login page, please continue to analyze it

**Comment by lyx3314844** [comment]
![Uploading EDB0A0281A258568BEA87C37B70935EC.jpg…]()

**Comment by lyx3314844** [comment]
![image](https://github.com/user-attachments/assets/9eab0e9c-3ddb-433c-8408-8bc1eff8952d)

**Comment by lyx3314844** [comment]
@ArtsiomCh 
   ![edb0a0281a258568bea87c37b70935ec](https://github.com/user-attachments/assets/bda1fdb1-6734-4938-8a9b-ddf891148368)

**Comment by lyx3314844** [comment]
![image](https://github.com/user-attachments/assets/350abb07-e7f7-45cd-af58-588885801191)
