### ISSUE TITLE
关于codium ai 在jetbrains 所有ide登录问题

### ISSUE THREAD

**Issue by lyx3314844** [Codium-ai/codiumai-jetbrains-release#255]
I have found that there are still some issues with the Codium AI website, only for users in China. Firstly, it is necessary to have a very good professional version system of Windows 10 or above, and it is necessary to prohibit the shutdown of proxies and firewalls. This is a necessary guarantee, as caching issues must be addressed every time the VPN is used up. There are three options for logging into Codium AI, and one option must be logged in continuously. Long term login is required to achieve success. I have tried multiple times and found that I am now getting error 404 or 401

**Comment by lyx3314844** [comment]
![image](https://github.com/user-attachments/assets/a84cd421-1750-4e09-aea7-be976e120c53)

**Comment by lyx3314844** [comment]
![image](https://github.com/user-attachments/assets/3ace38dc-5010-4c01-8a43-1b47a2ce9e62)

**Comment by lyx3314844** [comment]
![image](https://github.com/user-attachments/assets/bde97b94-9884-4473-a9b6-afca9758cf79)

**Comment by lyx3314844** [comment]
It is recommended to use the latest version of JetBrains IDE, which is version 2024.2.

**Comment by lyx3314844** [comment]
![image](https://github.com/user-attachments/assets/204514b0-f804-4408-8e9b-48a638ac2a0e)

**Comment by lyx3314844** [comment]
@@ArtsiomCh

**Comment by ArtsiomCh** [comment]
Glad to see you've been able to make it work through!

**Comment by lyx3314844** [comment]
@Mr. ArtsiomCh, Codeium AI still cannot be used in many plugins in JetBrains company. Could you please advise on how to completely solve this problem? Will your agents make any modifications in the future?
Can you help me take a look?
