### ISSUE TITLE
How to use AlphaCodinum

### ISSUE THREAD

**Issue by lyx3314844** [Codium-ai/codiumai-jetbrains-release#256]
How to use AlphaCodium, what are the differences between it and codium ai, and how to use it. Could you please inform me

**Comment by lyx3314844** [comment]
@ArtsiomCh

**Comment by ArtsiomCh** [comment]
@lyx3314844 this issue tracker is for CodiumAI plugin for Jetbrains IDEs
For any other questions please see docs at codium.ai and correspondent discord channel.
