### ISSUE TITLE
[0.9.3][ANDROID STUDIO Koala | 2024.1.1 Patch 2] JCEF is not supported.

### ISSUE THREAD

**Issue by psjiqi0** [Codium-ai/codiumai-jetbrains-release#262]
# User Description
JCEF is not supported.
Jcef version: 119.4.7-g55e15c8-chromium-119.0.6045.199-api-1.14 
JCefAppConfig.class is not from a JBR module, url: jar:file:/C:/Program%20Files/Android/Android%20Studio/lib/lib.jar!/com/jetbrains/cef/JCefAppConfig.class
requestId=2c937b7b-3988-427a-8d21-5d5b317aac21

# Stack Trace
```

```

# Other Information
```
=== About ===
Build version: Android Studio Koala | 2024.1.1 Patch 2 Build: #AI-241.18034.62.2411.12169540 August 1, 2024
Theme: Dark
JRE: 17.0.11+0--11852314, JetBrains s.r.o.
JVM: 17.0.11+0--11852314, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 10.0 (amd64)

=== Plugins ===
Custom plugins: [TONGYI Lingma - Your AI Coding Assistant. Type less, Code more. (1.3.10), Codiumate - Code, test and review with confidence - by CodiumAI (0.9.3)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Please follow propose fix and it should help:

> 1. Navigate to the Help -> Find Action... and find(type) "Registry". Here disable `ide.browser.jcef.sandbox.enable` option (and make sure `ide.browser.jcef.enabled` option is enabled);
>   2. Navigate to the Help -> Find Action... and find(type) "Choose Boot Runtime for the IDE" dialog. Here, you can select a boot runtime equipped with JCEF;
>   3. Restart the IDE.
