### ISSUE TITLE
[0.9.3][ANDROID STUDIO Koala | 2024.1.1 Patch 2] JCEF is not supported.

### ISSUE THREAD

**Issue by Ev5454** [Codium-ai/codiumai-jetbrains-release#267]
# User Description
JCEF is not supported.
Jcef version: 119.4.7-g55e15c8-chromium-119.0.6045.199-api-1.14 
JCefAppConfig.class is not from a JBR module, url: jar:file:/C:/Program%20Files/Android/Android%20Studio/lib/lib.jar!/com/jetbrains/cef/JCefAppConfig.class
requestId=e5c79765-fe38-4f34-8cdd-84659eddbc5e

# Stack Trace
```

```

# Other Information
```
=== About ===
Build version: Android Studio Koala | 2024.1.1 Patch 2 Build: #AI-241.18034.62.2411.12169540 August 1, 2024
Theme: Dark
JRE: 17.0.11+0--11852314, JetBrains s.r.o.
JVM: 17.0.11+0--11852314, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 10.0 (amd64)

=== Plugins ===
Custom plugins: [JetBrains Marketplace Licensing (241.18034.106), Cody: AI Coding Assistant with Autocomplete & Chat (6.0.26), Refact.ai (1.3.4), ChatGPT GPT-4 - Bito AI Code Assistant (1.3.8), CodeGPT (2.9.0-241.1), Codiumate - Code, test and review with confidence - by CodiumAI (0.9.3)]
Disabled plugins:[TONGYI Lingma - Your AI Coding Assistant. Type less, Code more. (1.3.11), Codeium: AI Autocomplete and Chat for Python, JS, Java, Go... (1.10.11), Machinet AI GPT-4 Chat and Unit Tests (2022.1.68), GitHub Copilot (1.5.19.6527), Tabnine: AI Code Completion & Chat in Java JS/TS Python & More (1.121.0), AICommit (3.1.0)]
```

**Comment by ArtsiomCh** [comment]
Please follow proposed fix and it should help:

> 1. Navigate to the Help -> Find Action... and find(type) "Registry". Here disable `ide.browser.jcef.sandbox.enable` option (and make sure `ide.browser.jcef.enabled` option is enabled);
>   2. Navigate to the Help -> Find Action... and find(type) "Choose Boot Runtime for the IDE" dialog. Here, you can select a boot runtime equipped with JCEF;
>   3. Restart the IDE.
