### ISSUE TITLE
[0.9.3][ANDROID STUDIO Koala | 2024.1.1 Patch 1] JCEF is not supported.

### ISSUE THREAD

**Issue by thangoghd** [Codium-ai/codiumai-jetbrains-release#269]
# User Description
JCEF is not supported.
Jcef version: 119.4.7-g55e15c8-chromium-119.0.6045.199-api-1.14 
JCefAppConfig.class is not from a JBR module, url: jar:file:/Applications/Android%20Studio.app/Contents/lib/lib.jar!/com/jetbrains/cef/JCefAppConfig.class
requestId=99ad6dab-92bc-42da-9dd2-30c092477f5a

# Stack Trace
```

```

# Other Information
```
=== About ===
Build version: Android Studio Koala | 2024.1.1 Patch 1 Build: #AI-241.18034.62.2411.12071903 July 11, 2024
Theme: Dark
JRE: 17.0.11+0-17.0.11b1207.24-11852314, JetBrains s.r.o.
JVM: 17.0.11+0-17.0.11b1207.24-11852314, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 12.7.6 (x86_64)

=== Plugins ===
Custom plugins: [Dart (241.18808), Codiumate - Code, test and review with confidence - by CodiumAI (0.9.3), Flutter (81.0.2)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Please follow proposed fix and it should help:

> 1. Navigate to the Help -> Find Action... and find(type) "Registry". Here disable `ide.browser.jcef.sandbox.enable` option (and make sure `ide.browser.jcef.enabled` option is enabled);
>   2. Navigate to the Help -> Find Action... and find(type) "Choose Boot Runtime for the IDE" dialog. Here, you can select a boot runtime equipped with JCEF;
>   3. Restart the IDE.
