### ISSUE TITLE
[0.9.3][ANDROID STUDIO Koala | 2024.1.1 Patch 1] JCEF is not supported.

### ISSUE THREAD

**Issue by OmidHaqi** [Codium-ai/codiumai-jetbrains-release#273]
# User Description
JCEF is not supported.
Jcef version: 119.4.7-g55e15c8-chromium-119.0.6045.199-api-1.14 
JCefAppConfig.class is not from a JBR module, url: jar:file:/opt/android-studio/lib/lib.jar!/com/jetbrains/cef/JCefAppConfig.class
requestId=e9bc9c86-e5fb-4589-8d3b-54bd316a1bed

# Stack Trace
```

```

# Other Information
```
=== About ===
Build version: Android Studio Koala | 2024.1.1 Patch 1 Build: #AI-241.18034.62.2411.12071903 July 11, 2024
Theme: GitHub Dark (Material)
JRE: 17.0.11+0-17.0.11b1207.24-11852314, JetBrains s.r.o.
JVM: 17.0.11+0-17.0.11b1207.24-11852314, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Linux 6.10.4-200.fc40.x86_64 (amd64)

=== Plugins ===
Custom plugins: [JsonToDart (JSON To Dart) (2.16), JetBrains Marketplace Licensing (241.18034.106), Dart (241.18808), Monokai Pro Theme (1.10), Rainbow Brackets (2024.2.6-241), Material Theme UI (9.3.1), Flutter (81.0.2), Atom Material Icons (97.0.0), Codiumate - Code, test and review with confidence - by CodiumAI (0.9.3)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Please follow proposed fix and it should help:

> 1. Navigate to the Help -> Find Action... and find(type) "Registry". Here disable `ide.browser.jcef.sandbox.enable` option (and make sure `ide.browser.jcef.enabled` option is enabled);
>   2. Navigate to the Help -> Find Action... and find(type) "Choose Boot Runtime for the IDE" dialog. Here, you can select a boot runtime equipped with JCEF;
>   3. Restart the IDE.
