### ISSUE TITLE
[0.9.3][ANDROID STUDIO Koala Feature Drop | 2024.1.2] JCEF is not supported.

### ISSUE THREAD

**Issue by maoude** [Codium-ai/codiumai-jetbrains-release#288]
no  `ide.browser.jcef.sandbox.enable` option in "Registry" to disable

and i think You are using us to debug you program 

# User Description
JCEF is not supported.
Jcef version: 119.4.7-g55e15c8-chromium-119.0.6045.199-api-1.14 
JCefAppConfig.class is not from a JBR module, url: jar:file:/C:/Program%20Files/Android/Android%20Studio/lib/lib.jar!/com/jetbrains/cef/JCefAppConfig.class
requestId=56ec9267-ac74-4964-a64d-37f053dffa33

# Stack Trace
```

```

# Other Information
```
=== About ===
Build version: Android Studio Koala Feature Drop | 2024.1.2 Build: #AI-241.18034.62.2412.12266719 August 23, 2024
Theme: Darcula
JRE: 17.0.11+0--11852314, JetBrains s.r.o.
JVM: 17.0.11+0--11852314, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [ClaudeMind (0.0.7), ChatGPT-Plus (3.3), Dart (241.18808), Gradle Dependency Helper (1.1), NexChatGPT - GPT4 China (ChatGPT-4 AI Assistant ChatGTP) (5.1.0), adb_idea (1.6.17), Gradle Repo (1.5), GitHub Copilot (1.5.20.6554), Codiumate - Code, test and review with confidence - by CodiumAI (0.9.3), Flutter (81.0.2)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Please follow proposed fix and it should help:

> 1. Navigate to the Help -> Find Action... and find(type) "Registry". Here disable `ide.browser.jcef.sandbox.enable` option (and make sure `ide.browser.jcef.enabled` option is enabled);
>   2. Navigate to the Help -> Find Action... and find(type) "Choose Boot Runtime for the IDE" dialog. Here, you can select a boot runtime equipped with JCEF;
>   3. Restart the IDE.
