### ISSUE TITLE
[0.9.3][ANDROID STUDIO Koala Feature Drop | 2024.1.2] JCEF is not supported.

### ISSUE THREAD

**Issue by wirlytornado246** [Codium-ai/codiumai-jetbrains-release#289]
# User Description
JCEF is not supported.
Jcef version: 119.4.7-g55e15c8-chromium-119.0.6045.199-api-1.14 
JCefAppConfig.class is not from a JBR module, url: jar:file:/C:/Program%20Files/Android/Android%20Studio/lib/lib.jar!/com/jetbrains/cef/JCefAppConfig.class
requestId=9c847a5c-03e9-4381-b8e6-ca07fff57131

# Stack Trace
```

```

# Other Information
```
=== About ===
Build version: Android Studio Koala Feature Drop | 2024.1.2 Build: #AI-241.18034.62.2412.12266719 August 22, 2024
Theme: Dark
JRE: 17.0.11+0--11852314, JetBrains s.r.o.
JVM: 17.0.11+0--11852314, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [JSON To Kotlin Class (JsonToKotlinClass) (3.7.4), Codiumate - Code, test and review with confidence - by CodiumAI (0.9.3)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Please follow proposed fix and it should help:

> 1. Navigate to the Help -> Find Action... and find(type) "Registry". Here disable `ide.browser.jcef.sandbox.enable` option (and make sure `ide.browser.jcef.enabled` option is enabled);
>   2. Navigate to the Help -> Find Action... and find(type) "Choose Boot Runtime for the IDE" dialog. Here, you can select a boot runtime equipped with JCEF;
>   3. Restart the IDE.
