### ISSUE TITLE
[0.9.3][ANDROID STUDIO Koala | 2024.1.1 Patch 1] JCEF is not supported.

### ISSUE THREAD

**Issue by msm00** [Codium-ai/codiumai-jetbrains-release#296]
# User Description
JCEF is not supported.
Jcef version: 119.4.7-g55e15c8-chromium-119.0.6045.199-api-1.14 
JCefAppConfig.class is not from a JBR module, url: jar:file:/Users/msm/Applications/Android%20Studio.app/Contents/lib/lib.jar!/com/jetbrains/cef/JCefAppConfig.class
requestId=19bca57d-9b37-4456-bc79-f1d23580390e

# Stack Trace
```

```

# Other Information
```
=== About ===
Build version: Android Studio Koala | 2024.1.1 Patch 1 Build: #AI-241.18034.62.2411.12071903 July 10, 2024
Theme: Darcula
JRE: 17.0.11+0-17.0.11b1207.24-11852314, JetBrains s.r.o.
JVM: 17.0.11+0-17.0.11b1207.24-11852314, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 14.5 (aarch64)

=== Plugins ===
Custom plugins: [Jetpack Compose UI Architecture Templates (1.3.2), Tabnine: AI Code Completion & Chat in Java JS/TS Python & More (1.126.0), Docker (241.18034.82), Codiumate - Code, test and review with confidence - by CodiumAI (0.9.3)]
Disabled plugins:[GitHub Copilot (1.5.20.6554)]
```

**Comment by ArtsiomCh** [comment]
Please follow proposed fix and it should help:

> 1. Navigate to the Help -> Find Action... and find(type) "Registry". Here disable `ide.browser.jcef.sandbox.enable` option (and make sure `ide.browser.jcef.enabled` option is enabled);
>   2. Navigate to the Help -> Find Action... and find(type) "Choose Boot Runtime for the IDE" dialog. Here, you can select a boot runtime equipped with JCEF;
>   3. Restart the IDE.
