### ISSUE TITLE
[0.9.4][INTELLIJ IDEA IC 2024.2.1] JCEF is not supported.

### ISSUE THREAD

**Issue by brunopnogueira92** [Codium-ai/codiumai-jetbrains-release#301]
# User Description
JCEF is not supported.
JCEF is manually disabled via 'ide.browser.jcef.enabled=false'
requestId=44578b66-c6a1-499d-a455-fb5d0cb4a05d

# Stack Trace
```

```

# Other Information
```
=== About ===
Build version: IntelliJ IDEA 2024.2.1 Build: #IC-242.21829.142 August 28, 2024
Theme: Light
JRE: 21.0.3+13-b509.11, JetBrains s.r.o.
JVM: 21.0.3+13-b509.11, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 10.0 (amd64)

=== Plugins ===
Custom plugins: [Resource Bundle Editor (242.20224.155), google-java-format (1.23.0.0), Jump to Line (0.1.16), Lombok (242.21829.142), Code Iris (2.4-beta), Angular Component Folding (1.5.0), Return Highlighter (0.8.3), Docker (242.21829.162), Maven Dependency Helper (2.5), GitLab (242.21829.162), Rainbow Brackets Lite - Free and OpenSource (1.2.0), JPA Buddy (2024.1.0-241), Azure Toolkit for IntelliJ (3.92.0-2024.2), GitHub Copilot (1.5.20.6554), Azure DevOps (1.162.2), GitToolBox (500.2.15+242), .ignore (4.5.3), SonarLint (10.9.0.79423), Codiumate - Code, test and review with confidence - by CodiumAI (0.9.4), Maven Helper (4.28.0-IJ2022.2)]
Disabled plugins:[]
```

**Comment by brunopnogueira92** [comment]
![imagem_2024-09-04_121610974](https://github.com/user-attachments/assets/97cd119c-9d28-49ed-a3c4-2d0d20a94aae)
![imagem_2024-09-04_121639536](https://github.com/user-attachments/assets/b8424570-ab60-4ea7-8d2b-17b403b21c60)

**Comment by brunopnogueira92** [comment]
I can't get the ide.browser.jcef.enabled option to be selected.

**Comment by ArtsiomCh** [comment]
@brunopnogueira92 why can't you enable ide.browser.jcef.enabled ?

**Comment by llq1020** [comment]
@ArtsiomCh 
When I check this option, it will still be automatically disabled after restart.
<img width="890" alt="image" src="https://github.com/user-attachments/assets/379804e6-7f48-4062-b347-ff137f15370f">

**Comment by ArtsiomCh** [comment]
You need to figure out why IDE disable it...
Do you use some kind of remote development configuration for your IDE?
