### ISSUE TITLE
[0.9.4][ANDROID STUDIO Ladybug | 2024.2.1 Canary 9] JCEF is not supported.

### ISSUE THREAD

**Issue by tz17012016** [Codium-ai/codiumai-jetbrains-release#304]
# User Description
JCEF is not supported.
Jcef version: 122.1.9-gd14e051-chromium-122.0.6261.94-api-1.17 
JCefAppConfig.class is not from a JBR module, url: jar:file:/C:/Program%20Files/Android/Android%20Studio/lib/lib.jar!/com/jetbrains/cef/JCefAppConfig.class
requestId=67147745-6f73-47f3-b253-e980e21dcb6d

# Stack Trace
```

```

# Other Information
```
=== About ===
Build version: Android Studio Ladybug | 2024.2.1 Canary 9 Build: #AI-242.20224.300.2421.12293307 August 29, 2024
Theme: Dark
JRE: 21.0.3+-12282718-b509.11, JetBrains s.r.o.
JVM: 21.0.3+-12282718-b509.11, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [Serial Port Monitor (242.20224.428), JetBrains Marketplace Licensing (242.20224.428), Lombok (242.20224.419), Codeium: AI Autocomplete and Chat for Python, JS, Java, Go... (1.14.14), Extra ToolWindow Colorful Icons (2024.4.1), Key Promoter X (2024.2.0), DragonBall ProgressBar (3.2), Database Navigator (3.4.4425.0), Rainbow Brackets (2024.2.6-241), Android Drawable Preview (1.1.10), adb_idea (1.6.18), Android Drawable Preview (1.1.6), Cody: AI Coding Assistant with Autocomplete & Chat (7.0.0), GitHub Copilot (1.5.20.6554), Atom Material Icons (97.0.0), .ignore (4.5.3), Codiumate - Code, test and review with confidence - by CodiumAI (0.9.4)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Please follow proposed fix and it should help:

> 1. Navigate to the Help -> Find Action... and find(type) "Registry". Here disable `ide.browser.jcef.sandbox.enable` option (and make sure `ide.browser.jcef.enabled` option is enabled);
>   2. Navigate to the Help -> Find Action... and find(type) "Choose Boot Runtime for the IDE" dialog. Here, you can select a boot runtime equipped with JCEF;
>   3. Restart the IDE.
