### ISSUE TITLE
[0.9.3][ANDROID STUDIO Iguana | 2023.2.1 Patch 2] JCEF is not supported.

### ISSUE THREAD

**Issue by Mhassaansi** [Codium-ai/codiumai-jetbrains-release#309]
# User Description
JCEF is not supported.
Jcef version: 111.2.1-g870da30-chromium-111.0.5563.64-api-1.12 
JCefAppConfig.class is not from a JBR module, url: jar:file:/C:/Program%20Files/Android/Android%20Studio/lib/lib.jar!/com/jetbrains/cef/JCefAppConfig.class
requestId=0af273ba-9885-471c-86a9-52afb3907371

# Stack Trace
```

```

# Other Information
```
=== About ===
Build version: Android Studio Iguana | 2023.2.1 Patch 2 Build: #AI-232.10300.40.2321.11668458 April 4, 2024
Theme: Light
JRE: 17.0.9+0--11185874, JetBrains s.r.o.
JVM: 17.0.9+0--11185874, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 10.0 (amd64)

=== Plugins ===
Custom plugins: [Kotlin Multiplatform Mobile (0.8.2(232)-20), Batch Scripts Support (1.0.13), JSON To Kotlin Class (JsonToKotlinClass) (3.7.4), Codiumate - Code, test and review with confidence - by CodiumAI (0.9.3), ADB Wi-Fi (1.2.6), JetBrains Marketplace Licensing (232.10300.41), GitHub Copilot (1.5.20.6554), Dart (232.10313), Flutter (79.0.1)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Please follow proposed fix and it should help:

> 1. Navigate to the Help -> Find Action... and find(type) "Registry". Here disable `ide.browser.jcef.sandbox.enable` option (and make sure `ide.browser.jcef.enabled` option is enabled);
>   2. Navigate to the Help -> Find Action... and find(type) "Choose Boot Runtime for the IDE" dialog. Here, you can select a boot runtime equipped with JCEF;
>   3. Restart the IDE.
