### ISSUE TITLE
[0.9.5][PHPSTORM 2024.1.4] JCEF is not supported.

### ISSUE THREAD

**Issue by postadelmaga** [Codium-ai/codiumai-jetbrains-release#312]
# User Description
JCEF is not supported.
Jcef version: 119.4.7-g55e15c8-chromium-119.0.6045.199-api-1.14 
JCefAppConfig.class is not from a JBR module, url: jar:file:/opt/phpstorm/lib/lib-client.jar!/com/jetbrains/cef/JCefAppConfig.class
requestId=50111d4a-1cf0-4bbf-829d-aa77816b4817

# Stack Trace
```

```

# Other Information
```
=== About ===
Build version: PhpStorm 2024.1.4 Build: #PS-241.18034.69 June 21, 2024
Theme: Dark
JRE: 22.0.2+9, Arch Linux
JVM: 22.0.2+9, OpenJDK 64-Bit Server VM, Arch Linux
Operating System: Linux 6.10.5-arch1-1 (amd64)

=== Plugins ===
Custom plugins: [JetBrains AI Assistant (241.18034.12), Magento PhpStorm (5.2.0), Codiumate - Code, test and review with confidence - by CodiumAI (0.9.5)]
Disabled plugins:[]
```

**Comment by ArtsiomCh** [comment]
Please follow proposed fix and it should help:

> 1. Navigate to the Help -> Find Action... and find(type) "Registry". Here disable `ide.browser.jcef.sandbox.enable` option (and make sure `ide.browser.jcef.enabled` option is enabled);
>   2. Navigate to the Help -> Find Action... and find(type) "Choose Boot Runtime for the IDE" dialog. Here, you can select a boot runtime equipped with JCEF;
>   3. Restart the IDE.
