### ISSUE TITLE
[0.9.5][ANDROID STUDIO Ladybug Feature Drop | 2024.2.2 Canary 1] JCEF is not supported.

### ISSUE THREAD

**Issue by hariomop12** [Codium-ai/codiumai-jetbrains-release#314]
# User Description
JCEF is not supported.
Jcef version: 122.1.9-gd14e051-chromium-122.0.6261.94-api-1.17 
JCefAppConfig.class is not from a JBR module, url: jar:file:/C:/Program%20Files/Android/Android%20Studio1/lib/lib.jar!/com/jetbrains/cef/JCefAppConfig.class
requestId=c30057f4-a50a-4455-b47e-ae7ef48a09b7

# Stack Trace
```

```

# Other Information
```
=== About ===
Build version: Android Studio Ladybug Feature Drop | 2024.2.2 Canary 1 Build: #AI-242.21829.142.2422.12329062 September 6, 2024
Theme: Dark
JRE: 21.0.3+-12282718-b509.11, JetBrains s.r.o.
JVM: 21.0.3+-12282718-b509.11, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [JetBrains Marketplace Licensing (242.21829.220), GitHub Copilot (1.5.21.6667), Codiumate - Code, test and review with confidence - by CodiumAI (0.9.5)]
Disabled plugins:[GitHub Actions Manager (2024.2.8), Machinet AI GPT-4 Chat and Unit Tests (2022.1.70)]
```

**Comment by ArtsiomCh** [comment]
Please follow proposed fix and it should help:

> 1. Navigate to the Help -> Find Action... and find(type) "Registry". Here disable `ide.browser.jcef.sandbox.enable` option (and make sure `ide.browser.jcef.enabled` option is enabled);
>   2. Navigate to the Help -> Find Action... and find(type) "Choose Boot Runtime for the IDE" dialog. Here, you can select a boot runtime equipped with JCEF;
>   3. Restart the IDE.
