### ISSUE TITLE
PHPStorm; CTRL + BACKSPACE not working

### ISSUE THREAD

**Issue by scheMeZa** [Codium-ai/codiumai-jetbrains-release#315]
Hello.

CTRL + Backspace is a keybind to delete a full word behind the carret.

This plugin has a shortcut assigned for CTRL + Backspace, which makes the PHPStorm one no longer work.

Please make the hotkeys configurable or disablable.

**Comment by ArtsiomCh** [comment]
We don't have any action assigned to CTRL + Backspace in our plugin
Could you please confirm it's coming from our plugin? (screenshot?)

**Comment by ArtsiomCh** [comment]
here we can see that CTRL + Backspace is assigned to default "delete the word start" with our plugin installed
![image](https://github.com/user-attachments/assets/254544dd-f4a6-4534-8498-65f858a4531c)

**Comment by scheMeZa** [comment]
Thank you for your quick response.

Please find attached the screenshot showing the CTRL + Backspace from Codium plugin, making the default keybind inoperable:
![image](https://github.com/user-attachments/assets/e059b9ea-d8a5-40e1-9d29-bfe9173150df)

**Comment by scheMeZa** [comment]
Just to be clear, it's the `undo` option causing issues.

The keybind is fine, but maybe only make it active when this window is open?

That way I can still delete word to start, with same keybind.

**Comment by ArtsiomCh** [comment]
The provided screenshot is for **Codeium** plugin and this our plugin is **Codiumate** (from CodiumAI)
Please contact Codeium plugin developers for support
