### ISSUE TITLE
Add support for light theme

### ISSUE THREAD

**Issue by mwajeeh** [Codium-ai/codiumai-jetbrains-release#338]
<img width="55" alt="Screenshot 2024-10-04 at 7 09 48 AM" src="https://github.com/user-attachments/assets/4f1dddc5-ad23-4d39-8476-b1a0161cef71">
<img width="54" alt="Screenshot 2024-10-04 at 7 09 41 AM" src="https://github.com/user-attachments/assets/7d0978f6-9d01-4234-81f0-a92815dcf662">

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Will be fixed in next version

**Comment by ArtsiomCh** [comment]
fixed in 0.10.1
