### ISSUE TITLE
Plugin not starting

### ISSUE THREAD

**Issue by ebertti** [Codium-ai/codiumai-jetbrains-release#348]
**Bug Description:**

I am experiencing an issue where the plugin frequently does not start correctly. In order to resolve this, I need to manually close PyCharm and restart it. However, in some cases, even restarting PyCharm isn't enough, and I need to manually terminate the process from the system's open processes.

**Steps to Reproduce:**

1. Open PyCharm and attempt to initialize the plugin.
2. The plugin often fails to start, with no error message displayed.
3. I close PyCharm and restart it to try again.
4. In some instances, the only way to get the plugin running again is to manually kill the process via the system.

**Expected Behavior:**

The plugin should start correctly upon opening PyCharm without requiring any manual intervention.

**Actual Behavior:**

The plugin fails to start intermittently, and sometimes I need to kill the process manually before I can get it to work.

**Environment Details:**

- **Machine:** Apple M1 Max
- **IDE:** PyCharm

Any assistance or fix for this issue would be greatly appreciated.

![image](https://github.com/user-attachments/assets/6d0a0b33-c81c-4022-9d96-8d2d8e38af54)

**Comment by ArtsiomCh** [comment]
This issue tracker is about Qodo Gen (formerly Codiumate)
And your screenshots are about Codeium plugin. Please contact Codeium plugin authors about your issue
