### ISSUE TITLE
Add .gitignore file and remove .DS_Store related stuff from repo 

### ISSUE THREAD

**Issue by IT-Cru** [Codium-ai/codiumai-jetbrains-release#57]
Similar to https://github.com/Codium-ai/codiumai-vscode-release/blob/main/.gitignore of CodiumAI VSCode extension.

┆Issue is synchronized with this [Trello card](https://trello.com/c/Nv3rxlsk) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
cc @GadiZimerman ?
