### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by damian-pastorini** [Codium-ai/codiumai-jetbrains-release#58]
A few good improvements would to be:
- A button to generate tests for an entire folder and specify a folder where the tests will be saved.
- An option to automatically install the selected test framework on the results folder so you can automatically run the tests after creation.
- The comments for the class analysis, methods and properties should be multi-line, right now you get a single line of text pretty bad to read.

┆Issue is synchronized with this [Trello card](https://trello.com/c/VXhjVKFZ) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
cc @GadiZimerman
