### ISSUE TITLE
Failure to authorize when trying to sign up

### ISSUE THREAD

**Issue by liber-tas** [Codium-ai/codiumai-jetbrains-release#6]
fter installing PyCharm plugin, clicked the "Sign in with Github", authorized the access at github, then I get this in the browser at the codium website:

401 Failed to Authorize.
Fail to create Mixpanel user: (redacted email)

And this in PyCharm:
![Screenshot from 2023-03-22 09-20-30](https://user-images.githubusercontent.com/579874/226917156-098d5900-f796-4d1a-af69-1c22b1080a82.png)

I also tried "Sign in with Google" using a different email address, and got the same result.

**Comment by ArtsiomCh** [comment]
Hi @liber-tas  
Thank you for reporting! Could you please try latest 0.4.5 version and let us know if you able to sign in?

**Comment by liber-tas** [comment]
I upgraded to 0.4.5, still having the same issue. Here's the URL in the browser BTW, goes to localhost which seems a bit... off:

http://localhost:63342/codium.codium?provider=google&token=eyJhb... (token abbreviated)

**Comment by ArtsiomCh** [comment]
Interesting...
Do you have any firewall that could block some connections?
Would you mind to collect [log](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files)  and send it to me (privately) please?
PS localhost is fine here, we need to do redirect back to ide from auth provider.

**Comment by liber-tas** [comment]
@ArtsiomCh - how do I send the log to you privately?

**Comment by liber-tas** [comment]
Here is an error that seems related:

023-03-22 16:56:15,003 [12464652]   INFO - #codeium.y - [Language Server]: E0322 16:56:14.987926 808948 unleash.go:33] Unleash error: Get "https://unleash.codeium.com/api/client/features": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023-03-22 16:56:15,003 [12464652]   INFO - #codeium.y - [Language Server]: 

The above is surrounded by call to: 2023-03-22 16:56:23,276 [12472925]   INFO - okhttp3.OkHttpClient - --> POST https://identitytoolkit.googleapis.com/v1/accounts:....

**Comment by ArtsiomCh** [comment]
> @ArtsiomCh - how do I send the log to you privately?

achapialiou@gmail.com sorry, I thought GitHub has ability to send pm but apparently it's not...
First INFO is not ours, but second it is. But need to see at least what's around it.
Also if you'll enable debug log level for our classes before collecting log, that would help a lot:
1. Open Help | Diagnostic Tools | Debug Log Settings...

2. Add the  following line: 
`#ai.codium`

3. Click OK

4. Reproduce the problem.

**Comment by ArtsiomCh** [comment]
@liber-tas please try that 0.4.6-qa1 version with fix:
[codium-ai-plugin-0.4.6-qa1.zip](https://github.com/Codium-ai/codiumai-jetbrains-release/files/11048716/codium-ai-plugin-0.4.6-qa1.zip)
And let me know please if it helps.

**Comment by ArtsiomCh** [comment]
@liber-tas Please don't forget to remove that `#ai.codium` from Debug Log Settings otherwise JetBrains (and other plugin) devs will hate us for overcrowded logs :)

**Comment by liber-tas** [comment]
Good catch - I would have left it there - thanks!
