### ISSUE TITLE
Not getting the generate test option

### ISSUE THREAD

**Issue by meza** [Codium-ai/codiumai-jetbrains-release#7]
Hey, it might be that Codium doesn't quite understand this syntax but I'm not getting the prompt to generate tests.
Latest IntelliJ Idea on WSL2

![image](https://user-images.githubusercontent.com/211977/227241691-8aadb9b5-e620-4596-ac3a-13cfd40b068d.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/15dGaazG) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Could you please try it on some "normal" function, not the arrow one?
Anyway will try to reproduce with your code (any chance it's open source project?)
And wsl should not be the case afaik.

**Comment by meza** [comment]
I tried it on normal functions, same issue. Works well if I'm on windows, intelliJ is on windows and the code is on windows.
However when the code and the host is on WSL and the client is on windows, it doesn't

**Comment by DedyKredo** [comment]
OK, we'll look into it, might take a bit but please bear with us!
