### ISSUE TITLE
[Feature Request] Analyze existing tests 

### ISSUE THREAD

**Issue by esauser** [Codium-ai/codiumai-jetbrains-release#71]
We'd like the plugin to be aware of existing tests when indicating covered behaviors and suggesting new tests to cover missed behaviors.  Additionally, it could become aware of the test style, where they are located, etc. to help generate better tests.

┆Issue is synchronized with this [Trello card](https://trello.com/c/5AjPUIvc) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Thanks for good proposal!
cc @GadiZimerman

**Comment by GadiZimerman** [comment]
We are working to add support to the scenario where we're starting from an existing test suite
