### ISSUE TITLE
[Feature Request] Provide all code suggestions 

### ISSUE THREAD

**Issue by esauser** [Codium-ai/codiumai-jetbrains-release#74]
Currently we have to specify a number of code suggestions.  We'd like to see all code suggestions.

┆Issue is synchronized with this [Trello card](https://trello.com/c/JPgZbz7m) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Thanks for contacting us.
Where  do you need to specify the number of code suggestions? 
All of them shown and you can select as many (or All of them) to generate code changes:
![image](https://github.com/Codium-ai/codiumai-jetbrains-release/assets/14268320/db4b4237-ec64-4096-b51c-e456d100f1b2)

**Comment by esauser** [comment]
Sorry, it isn't a number.  Instead, you have to click more.  Can we just get all of them?  
<img width="565" alt="image" src="https://github.com/Codium-ai/codiumai-jetbrains-release/assets/24945592/8c64e5f8-6b6c-4095-92c5-da23d28ed339">

**Comment by ArtsiomCh** [comment]
cc @GadiZimerman

**Comment by GadiZimerman** [comment]
The number of suggestions isn't constant, it is suggested by our backend. You can add suggestions manually but their priority usually decreases. at some point they may even become redundant, so usually 1-2 additional clicks on "more suggestions" should suffice. Controling the number of suggestions isn't on our roadmap but we may reconsider if more user surface this up.
