### ISSUE TITLE
[BUG] Auto complete seems to break after python remote debug session

### ISSUE THREAD

**Issue by alabamagan** [Codium-ai/codiumai-jetbrains-release#75]
Excuse me if this is not the right place to report autocomplete related error in JetBrains. The bug I am reporting is not related to CodiumAI unit test generator.

# Ways to replicate:
1. In pycharm, starts a debug session
2. During debug session, type something into the console
3. Suggestion stops working and loading icon is shown forever in the status bar.

# Tried and didn't work
* Disable and enable CodiumAI again -> The loading icon would be briefly gone and go back to '{...}' state, but when typing in the editor, there's the loading icon again.

# Tried and worked
* Restart pycharm

┆Issue is synchronized with this [Trello card](https://trello.com/c/2ySBW3MV) by [Unito](https://www.unito.io)

**Comment by aldanchenko** [comment]
Hi @alabamagan 👋

Thanks for contacting us.


So if you disable CodiumAI plugin this problem not exist?

Best regards,
Alex

**Comment by alabamagan** [comment]
Hi @aldanchenko, thanks for looking into this. 

I cannot determine if disabling the plugin through Jetbrain's setting and re-enabling it would solve the problem because it would request a restart of the PyCharm IDE. Restarting will reliable restore the auto complete even without disabling the plugin.

But if you mean disabling the plugin through the right-click pop-up options and re-enabling it then no, it didn't solve the problem.

**Comment by aldanchenko** [comment]
Hi @alabamagan 

I see. Thank you! I will try to reproduce it.

Best regards,
Alex

**Comment by ArtsiomCh** [comment]
The issue seems to not relate to CodiumAI plugin but instead to PyCharm IDE itself.
Please, report in JetBrains bug tracker: https://youtrack.jetbrains.com/

**Comment by alabamagan** [comment]
> The issue seems to not relate to CodiumAI plugin but instead to PyCharm IDE itself. Please, report in JetBrains bug tracker: https://youtrack.jetbrains.com/

Thanks for looking into this! Any clue what might be triggering this error? Also is there a way I can dive into the Codium's info log?

**Comment by ArtsiomCh** [comment]
Could be numerous reasons for that issue. better ask/report to JetBrains team.
The Idea logs could be found [that way](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files)
