### ISSUE TITLE
vitest support for ts/js

### ISSUE THREAD

**Issue by meza** [Codium-ai/codiumai-jetbrains-release#8]
[Vitest](https://vitest.dev/) is more and more popular with the modern JS world as it has native ESM support and performs faster than jest does. The API is pretty much identical aside from a few things.

It would be nice if Codium would support it

┆Issue is synchronized with this [Trello card](https://trello.com/c/sUMGXXec) by [Unito](https://www.unito.io)

**Comment by DedyKredo** [comment]
Thanks @meza ! We'll definitely look into it and will update here in the coming days.

**Comment by ohbob** [comment]
Is playwright coming to the Test framework selection? I don't use any of the available from the js list.

**Comment by oranshiner** [comment]
Hey @meza and @ohbob, 
Currently, we have yet to make plans to support these programming languages. However, we will let you know if they become available in our Discord channel
