### ISSUE TITLE
In PyCharm, getting error every time trying to generate test cases

### ISSUE THREAD

**Issue by mifas** [Codium-ai/codiumai-jetbrains-release#9]
As title says, below is the error. tried multiple times uninstalling and installing. 
`Failed to execute 'https://securetoken.googleapis.com/v1/token' network request: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

And is there way to reset authentication?

┆Issue is synchronized with this [Trello card](https://trello.com/c/dhBfGMrm) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Seems like problems with Google SSL certificate verification.
Are you behind any proxy that might replace certificates ?
Why do you need reset auth? Did you eventually be able to signing successfully?

**Comment by mifas** [comment]
> Are you behind any proxy that might replace certificates?
No. 

> Why do you need reset auth? Did you eventually be able to signing successfully?
I want to change the login

**Comment by almog-lv** [comment]
@mifas we are still looking for this issue, were you able to login eventually?
